### PR TITLE
1.26.1

### PR DESCRIPTION
**Pull request by timsmeets23**
I updated your work so people could use your amazing tool again.
Temp Download link: https://github.com/timsmeets23/Orange-Juice/releases/download/1.26.1/999.Orange.Juice.Steam.1.26.1.zip

### CODE REVIEW

**Comment by NintendoFan** [comment]
Do you know the offsets for the 1.26.2 revision, I'm too dumb to find them myself :(

**Comment by timsmeets23** [comment]
I'll work on it today or tomorrow.

**Comment by NintendoFan** [comment]
Any luck yet?

**Comment by timsmeets23** [comment]
Just published the update

**Pull request closed without merging**
